export type ParasiteScanHit = {
  diseaseId: string;
  diseaseName: string;
  status: string;
  targetSymbol: string | null;
  targetName: string | null;
  targetRank: number | null;
  targetScore: number | null;
  moleculeHint: string | null;
  evidenceTier?: string | null;
  datasetSource?: string | null;
  interactionMethod?: string | null;
  interactionType?: string | null;
  pathogenTaxon?: string | null;
  pathogenInteractor?: string | null;
  pmid: string | null;
  title: string | null;
  url: string | null;
  hitTargetCount: number;
};

export const parasiteScanMetadata = {
  "generatedAt": "2026-05-15T15:36:54Z",
  "totalIndications": 38,
  "openTargetsTargetLimit": 100,
  "parasiteRetmax": 6,
  "hpidbOnly": true,
  "hpidbLoadedRows": 2809,
  "hpidbIndexedHostIdentifiers": 21294
} as const;

export const parasiteScanHits = [
  {
    "diseaseId": "graft-versus-host-disease",
    "diseaseName": "Graft-versus-host disease",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JAK1",
    "targetName": "Janus kinase 1",
    "targetRank": 2,
    "targetScore": 0.5372879669579735,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045592",
    "pmid": "24009866",
    "title": "intact:EBI-8781875|imex:IM-25847-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24009866/",
    "hitTargetCount": 24
  },
  {
    "diseaseId": "dermatomyositis",
    "diseaseName": "Dermatomyositis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JAK1",
    "targetName": "Janus kinase 1",
    "targetRank": 2,
    "targetScore": 0.34891052075541223,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045592",
    "pmid": "24009866",
    "title": "intact:EBI-8781875|imex:IM-25847-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24009866/",
    "hitTargetCount": 14
  },
  {
    "diseaseId": "adult-onset-still-s-disease",
    "diseaseName": "Adult-onset Still's disease",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "TLR2",
    "targetName": "toll like receptor 2",
    "targetRank": 23,
    "targetScore": 0.07668781984707562,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "confocal microscopy",
    "interactionType": "colocalization",
    "pathogenTaxon": "Hepatitis C virus genotype 1a (isolate H77)",
    "pathogenInteractor": "Hepatitis C virus genotype 1a (isolate H77) protein p27958-pro_0000037566",
    "pmid": "15521019",
    "title": "intact:EBI-6914676|imex:IM-25878-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/15521019/",
    "hitTargetCount": 20
  },
  {
    "diseaseId": "scleroderma-limited",
    "diseaseName": "Scleroderma | limited",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "STAT1",
    "targetName": "signal transducer and activator of transcription 1",
    "targetRank": 8,
    "targetScore": 0.06642692231266031,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "anti tag coimmunoprecipitation",
    "interactionType": "physical association",
    "pathogenTaxon": "Bovine herpesvirus 1",
    "pathogenInteractor": "Bovine herpesvirus 1 protein UL47",
    "pmid": "26889034",
    "title": "intact:EBI-11896624|imex:IM-25966-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/26889034/",
    "hitTargetCount": 9
  },
  {
    "diseaseId": "polymyositis",
    "diseaseName": "Polymyositis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JAK1",
    "targetName": "Janus kinase 1",
    "targetRank": 3,
    "targetScore": 0.3486745298958179,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045592",
    "pmid": "24009866",
    "title": "intact:EBI-8781875|imex:IM-25847-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24009866/",
    "hitTargetCount": 14
  },
  {
    "diseaseId": "juvenile-idiopathic-arthritis",
    "diseaseName": "Juvenile idiopathic arthritis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "PTGS2",
    "targetName": "prostaglandin-endoperoxide synthase 2",
    "targetRank": 3,
    "targetScore": 0.6074014312680375,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "two hybrid",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 1b (isolate Con1) (HCV)",
    "pathogenInteractor": "Hepatitis C virus genotype 1b (isolate Con1) (HCV) protein q9wmx2-pro_0000037550",
    "pmid": "20953506",
    "title": "intact:EBI-9083640|imex:IM-26075-91",
    "url": "https://pubmed.ncbi.nlm.nih.gov/20953506/",
    "hitTargetCount": 6
  },
  {
    "diseaseId": "antisynthetase-syndrome",
    "diseaseName": "Antisynthetase syndrome",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "ACTB",
    "targetName": "actin beta",
    "targetRank": 8,
    "targetScore": 0.017801429667313136,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "anti bait coimmunoprecipitation",
    "interactionType": "association",
    "pathogenTaxon": "Human herpesvirus 1",
    "pathogenInteractor": "Human herpesvirus 1 protein UL54",
    "pmid": "15567442",
    "title": "intact:EBI-10766007|imex:IM-26011-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/15567442/",
    "hitTargetCount": 21
  },
  {
    "diseaseId": "igg4-related-disease",
    "diseaseName": "IgG4-related disease",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "RPL17",
    "targetName": "ribosomal protein L17",
    "targetRank": 10,
    "targetScore": 0.10261797292773887,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "association",
    "pathogenTaxon": "Classical swine fever virus",
    "pathogenInteractor": "Classical swine fever virus protein p19712-pro_0000038050",
    "pmid": "24965446",
    "title": "intact:EBI-10901232|imex:IM-25926-21",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24965446/",
    "hitTargetCount": 8
  },
  {
    "diseaseId": "scleroderma-systemic",
    "diseaseName": "Scleroderma | systemic",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "FGFR4",
    "targetName": "fibroblast growth factor receptor 4",
    "targetRank": 9,
    "targetScore": 0.5220232291954109,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "anti tag coimmunoprecipitation",
    "interactionType": "association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045602",
    "pmid": "25616068",
    "title": "intact:EBI-11599650|imex:IM-26093-13",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25616068/",
    "hitTargetCount": 13
  },
  {
    "diseaseId": "iga-vasculitis",
    "diseaseName": "IgA vasculitis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "PSMA6",
    "targetName": "proteasome 20S subunit alpha 6",
    "targetRank": 27,
    "targetScore": 0.014783194187388075,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "two hybrid",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 1b (isolate Con1) (HCV)",
    "pathogenInteractor": "Hepatitis C virus genotype 1b (isolate Con1) (HCV) protein q9wmx2-pro_0000037545",
    "pmid": "18985028",
    "title": "intact:EBI-9078412|imex:IM-25957-261",
    "url": "https://pubmed.ncbi.nlm.nih.gov/18985028/",
    "hitTargetCount": 23
  },
  {
    "diseaseId": "kawasaki-disease",
    "diseaseName": "Kawasaki disease",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "PTGS2",
    "targetName": "prostaglandin-endoperoxide synthase 2",
    "targetRank": 10,
    "targetScore": 0.3270422400212,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "two hybrid",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 1b (isolate Con1) (HCV)",
    "pathogenInteractor": "Hepatitis C virus genotype 1b (isolate Con1) (HCV) protein q9wmx2-pro_0000037550",
    "pmid": "20953506",
    "title": "intact:EBI-9083640|imex:IM-26075-91",
    "url": "https://pubmed.ncbi.nlm.nih.gov/20953506/",
    "hitTargetCount": 19
  },
  {
    "diseaseId": "sapho-syndrome",
    "diseaseName": "SAPHO syndrome",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "PPP2R2D",
    "targetName": "protein phosphatase 2 regulatory subunit Bdelta",
    "targetRank": 5,
    "targetScore": 0.19472631409049848,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "affinity technology",
    "interactionType": "association",
    "pathogenTaxon": "Human herpesvirus 8 (HHV-8)",
    "pathogenInteractor": "Human herpesvirus 8 (HHV-8) protein ORF2",
    "pmid": "25544563",
    "title": "intact:EBI-14062817|imex:IM-26114-65",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25544563/",
    "hitTargetCount": 27
  },
  {
    "diseaseId": "sj-gren-syndrome",
    "diseaseName": "Sj\u00f6gren syndrome",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "GTF2I",
    "targetName": "general transcription factor IIi",
    "targetRank": 9,
    "targetScore": 0.35880983633442,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "affinity technology",
    "interactionType": "association",
    "pathogenTaxon": "Human herpesvirus 8 (HHV-8)",
    "pathogenInteractor": "Human herpesvirus 8 (HHV-8) protein K8.1",
    "pmid": "25544563",
    "title": "intact:EBI-14062552|imex:IM-26114-47",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25544563/",
    "hitTargetCount": 8
  },
  {
    "diseaseId": "takayasu-arteritis",
    "diseaseName": "Takayasu arteritis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JAK1",
    "targetName": "Janus kinase 1",
    "targetRank": 9,
    "targetScore": 0.2795871600689769,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045592",
    "pmid": "24009866",
    "title": "intact:EBI-8781875|imex:IM-25847-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24009866/",
    "hitTargetCount": 15
  },
  {
    "diseaseId": "hypersensitivity-vasculitis",
    "diseaseName": "Hypersensitivity vasculitis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "PSAP",
    "targetName": "prosaposin",
    "targetRank": 5,
    "targetScore": 0.01810941287955039,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "affinity chromatography technology",
    "interactionType": "physical association",
    "pathogenTaxon": "Mycoplasma pneumoniae (strain ATCC 29342 / M129)",
    "pathogenInteractor": "Mycoplasma pneumoniae (strain ATCC 29342 / M129) protein cards",
    "pmid": "15845487",
    "title": "intact:EBI-13483417|imex:IM-25892-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/15845487/",
    "hitTargetCount": 37
  },
  {
    "diseaseId": "mixed-connective-tissue-disease",
    "diseaseName": "Mixed connective tissue disease",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "TRAP1",
    "targetName": "TNF receptor associated protein 1",
    "targetRank": 2,
    "targetScore": 0.32779784471481044,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "anti tag coimmunoprecipitation",
    "interactionType": "association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045597",
    "pmid": "25616068",
    "title": "intact:EBI-11599782|imex:IM-26093-17",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25616068/",
    "hitTargetCount": 13
  },
  {
    "diseaseId": "reactive-arthritis",
    "diseaseName": "Reactive arthritis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JUN",
    "targetName": "Jun proto-oncogene, AP-1 transcription factor subunit",
    "targetRank": 20,
    "targetScore": 0.016631093460811583,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "peptide array",
    "interactionType": "direct interaction",
    "pathogenTaxon": "Human T-cell leukemia virus 1 (strain Japan ATK-1 subtype A)",
    "pathogenInteractor": "Human T-cell leukemia virus 1 (strain Japan ATK-1 subtype A) protein HBZ",
    "pmid": "20102225",
    "title": "intact:EBI-10890333|imex:IM-25853-241",
    "url": "https://pubmed.ncbi.nlm.nih.gov/20102225/",
    "hitTargetCount": 40
  },
  {
    "diseaseId": "palindromic-rheumatism",
    "diseaseName": "Palindromic rheumatism",
    "status": "no-parasite-hit-in-top-ranked-targets",
    "evidenceTier": "no-parasite-hit-in-top-ranked-targets",
    "targetSymbol": null,
    "targetName": null,
    "targetRank": null,
    "targetScore": null,
    "moleculeHint": null,
    "datasetSource": null,
    "interactionMethod": null,
    "interactionType": null,
    "pathogenTaxon": null,
    "pathogenInteractor": null,
    "pmid": null,
    "title": null,
    "url": null,
    "hitTargetCount": 0
  },
  {
    "diseaseId": "polyarteritis-nodosa",
    "diseaseName": "Polyarteritis nodosa",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "VANGL1",
    "targetName": "VANGL planar cell polarity protein 1",
    "targetRank": 15,
    "targetScore": 0.29609838175802555,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "affinity technology",
    "interactionType": "association",
    "pathogenTaxon": "Human herpesvirus 8 (HHV-8)",
    "pathogenInteractor": "Human herpesvirus 8 (HHV-8) protein K8.1",
    "pmid": "25544563",
    "title": "intact:EBI-14062552|imex:IM-26114-47",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25544563/",
    "hitTargetCount": 6
  },
  {
    "diseaseId": "giant-cell-arteritis",
    "diseaseName": "Giant cell arteritis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "PLG",
    "targetName": "plasminogen",
    "targetRank": 2,
    "targetScore": 0.4033360541836309,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "enzyme linked immunosorbent assay",
    "interactionType": "physical association",
    "pathogenTaxon": "Mycoplasma pneumoniae (strain ATCC 29342 / M129)",
    "pathogenInteractor": "Mycoplasma pneumoniae (strain ATCC 29342 / M129) protein pdhA",
    "pmid": "26667841",
    "title": "intact:EBI-12654874|imex:IM-26055-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/26667841/",
    "hitTargetCount": 18
  },
  {
    "diseaseId": "eosinophilic-granulomatosis-with-polyangiitis",
    "diseaseName": "Eosinophilic granulomatosis with polyangiitis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "CD83",
    "targetName": "CD83 molecule",
    "targetRank": 19,
    "targetScore": 0.048045381109011236,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "two hybrid",
    "interactionType": "physical association",
    "pathogenTaxon": "Escherichia coli",
    "pathogenInteractor": "Escherichia coli protein sepZ",
    "pmid": "20374249",
    "title": "intact:EBI-14022510|imex:IM-25964-11",
    "url": "https://pubmed.ncbi.nlm.nih.gov/20374249/",
    "hitTargetCount": 14
  },
  {
    "diseaseId": "beh-et-s-disease",
    "diseaseName": "Beh\u00e7et's Disease",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "CDK6",
    "targetName": "cyclin dependent kinase 6",
    "targetRank": 13,
    "targetScore": 0.4209514544858753,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "affinity technology",
    "interactionType": "association",
    "pathogenTaxon": "Human herpesvirus 8 (HHV-8)",
    "pathogenInteractor": "Human herpesvirus 8 (HHV-8) protein ORF72",
    "pmid": "25544563",
    "title": "intact:EBI-14064226|imex:IM-26114-139",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25544563/",
    "hitTargetCount": 13
  },
  {
    "diseaseId": "cryoglobulinemia",
    "diseaseName": "Cryoglobulinemia",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "C4A",
    "targetName": "complement C4A (Chido/Rodgers blood group)",
    "targetRank": 6,
    "targetScore": 0.02424419761602146,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "affinity technology",
    "interactionType": "association",
    "pathogenTaxon": "Human herpesvirus 8 (HHV-8)",
    "pathogenInteractor": "Human herpesvirus 8 (HHV-8) protein ORF4",
    "pmid": "25544563",
    "title": "intact:EBI-14063444|imex:IM-26114-55",
    "url": "https://pubmed.ncbi.nlm.nih.gov/25544563/",
    "hitTargetCount": 25
  },
  {
    "diseaseId": "multisystem-inflammatory-syndrome-in-children",
    "diseaseName": "Multisystem inflammatory syndrome in children",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "RPL17",
    "targetName": "ribosomal protein L17",
    "targetRank": 15,
    "targetScore": 0.012370659024862934,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "association",
    "pathogenTaxon": "Classical swine fever virus",
    "pathogenInteractor": "Classical swine fever virus protein p19712-pro_0000038050",
    "pmid": "24965446",
    "title": "intact:EBI-10901232|imex:IM-25926-21",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24965446/",
    "hitTargetCount": 24
  },
  {
    "diseaseId": "cogan-syndrome",
    "diseaseName": "Cogan syndrome",
    "status": "no-open-targets-ranked-targets",
    "evidenceTier": "no-open-targets-ranked-targets",
    "targetSymbol": null,
    "targetName": null,
    "targetRank": null,
    "targetScore": null,
    "moleculeHint": null,
    "datasetSource": null,
    "interactionMethod": null,
    "interactionType": null,
    "pathogenTaxon": null,
    "pathogenInteractor": null,
    "pmid": null,
    "title": null,
    "url": null,
    "hitTargetCount": 0
  },
  {
    "diseaseId": "jaccoud-arthropathy",
    "diseaseName": "Jaccoud arthropathy",
    "status": "no-open-targets-ranked-targets",
    "evidenceTier": "no-open-targets-ranked-targets",
    "targetSymbol": null,
    "targetName": null,
    "targetRank": null,
    "targetScore": null,
    "moleculeHint": null,
    "datasetSource": null,
    "interactionMethod": null,
    "interactionType": null,
    "pathogenTaxon": null,
    "pathogenInteractor": null,
    "pmid": null,
    "title": null,
    "url": null,
    "hitTargetCount": 0
  },
  {
    "diseaseId": "mikulicz-disease",
    "diseaseName": "Mikulicz disease",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "FAS",
    "targetName": "Fas cell surface death receptor",
    "targetRank": 1,
    "targetScore": 0.04640444655421115,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "anti bait coimmunoprecipitation",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045603",
    "pmid": "23427160",
    "title": "intact:EBI-8840058|imex:IM-26063-7",
    "url": "https://pubmed.ncbi.nlm.nih.gov/23427160/",
    "hitTargetCount": 8
  },
  {
    "diseaseId": "autoimmune-lymphoproliferative-syndrome",
    "diseaseName": "Autoimmune lymphoproliferative syndrome",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "FAS",
    "targetName": "Fas cell surface death receptor",
    "targetRank": 1,
    "targetScore": 0.7987668205072785,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "anti bait coimmunoprecipitation",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045603",
    "pmid": "23427160",
    "title": "intact:EBI-8840058|imex:IM-26063-7",
    "url": "https://pubmed.ncbi.nlm.nih.gov/23427160/",
    "hitTargetCount": 8
  },
  {
    "diseaseId": "heerfordt-syndrome",
    "diseaseName": "Heerfordt syndrome",
    "status": "no-parasite-hit-in-top-ranked-targets",
    "evidenceTier": "no-parasite-hit-in-top-ranked-targets",
    "targetSymbol": null,
    "targetName": null,
    "targetRank": null,
    "targetScore": null,
    "moleculeHint": null,
    "datasetSource": null,
    "interactionMethod": null,
    "interactionType": null,
    "pathogenTaxon": null,
    "pathogenInteractor": null,
    "pmid": null,
    "title": null,
    "url": null,
    "hitTargetCount": 0
  },
  {
    "diseaseId": "eosinophilia-myalgia-syndrome",
    "diseaseName": "Eosinophilia-myalgia syndrome",
    "status": "no-parasite-hit-in-top-ranked-targets",
    "evidenceTier": "no-parasite-hit-in-top-ranked-targets",
    "targetSymbol": null,
    "targetName": null,
    "targetRank": null,
    "targetScore": null,
    "moleculeHint": null,
    "datasetSource": null,
    "interactionMethod": null,
    "interactionType": null,
    "pathogenTaxon": null,
    "pathogenInteractor": null,
    "pmid": null,
    "title": null,
    "url": null,
    "hitTargetCount": 0
  },
  {
    "diseaseId": "granulomatous-myositis",
    "diseaseName": "Granulomatous myositis",
    "status": "no-open-targets-ranked-targets",
    "evidenceTier": "no-open-targets-ranked-targets",
    "targetSymbol": null,
    "targetName": null,
    "targetRank": null,
    "targetScore": null,
    "moleculeHint": null,
    "datasetSource": null,
    "interactionMethod": null,
    "interactionType": null,
    "pathogenTaxon": null,
    "pathogenInteractor": null,
    "pmid": null,
    "title": null,
    "url": null,
    "hitTargetCount": 0
  },
  {
    "diseaseId": "relapsing-polychondritis",
    "diseaseName": "Relapsing polychondritis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "MGP",
    "targetName": "matrix Gla protein",
    "targetRank": 17,
    "targetScore": 0.0073915970936940375,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "two hybrid",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 1a (isolate H77)",
    "pathogenInteractor": "Hepatitis C virus genotype 1a (isolate H77) protein p27958-pro_0000037576",
    "pmid": "15607035",
    "title": "intact:EBI-9105679|imex:IM-25884-41",
    "url": "https://pubmed.ncbi.nlm.nih.gov/15607035/",
    "hitTargetCount": 5
  },
  {
    "diseaseId": "rheumatoid-arthritis",
    "diseaseName": "Rheumatoid arthritis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JAK1",
    "targetName": "Janus kinase 1",
    "targetRank": 8,
    "targetScore": 0.6903808968126417,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045592",
    "pmid": "24009866",
    "title": "intact:EBI-8781875|imex:IM-25847-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24009866/",
    "hitTargetCount": 5
  },
  {
    "diseaseId": "lupus-erythematosus-systemic",
    "diseaseName": "Lupus erythematosus | systemic",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "IKBKE",
    "targetName": "inhibitor of nuclear factor kappa B kinase subunit epsilon",
    "targetRank": 36,
    "targetScore": 0.4697123784704897,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepacivirus hominis",
    "pathogenInteractor": "Hepacivirus hominis protein k7y1a2_9hepc",
    "pmid": "23096996",
    "title": "intact:EBI-8788684|imex:IM-26017-9",
    "url": "https://pubmed.ncbi.nlm.nih.gov/23096996/",
    "hitTargetCount": 13
  },
  {
    "diseaseId": "polymyalgia-rheumatica",
    "diseaseName": "Polymyalgia rheumatica",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JAK1",
    "targetName": "Janus kinase 1",
    "targetRank": 18,
    "targetScore": 0.27755447086821106,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045592",
    "pmid": "24009866",
    "title": "intact:EBI-8781875|imex:IM-25847-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24009866/",
    "hitTargetCount": 9
  },
  {
    "diseaseId": "ankylosing-spondylitis",
    "diseaseName": "Ankylosing spondylitis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "PTGS2",
    "targetName": "prostaglandin-endoperoxide synthase 2",
    "targetRank": 2,
    "targetScore": 0.6089041866925968,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "two hybrid",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 1b (isolate Con1) (HCV)",
    "pathogenInteractor": "Hepatitis C virus genotype 1b (isolate Con1) (HCV) protein q9wmx2-pro_0000037550",
    "pmid": "20953506",
    "title": "intact:EBI-9083640|imex:IM-26075-91",
    "url": "https://pubmed.ncbi.nlm.nih.gov/20953506/",
    "hitTargetCount": 5
  },
  {
    "diseaseId": "psoriatic-arthritis",
    "diseaseName": "Psoriatic arthritis",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "JAK1",
    "targetName": "Janus kinase 1",
    "targetRank": 14,
    "targetScore": 0.5247851160027918,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "pull down",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045592",
    "pmid": "24009866",
    "title": "intact:EBI-8781875|imex:IM-25847-1",
    "url": "https://pubmed.ncbi.nlm.nih.gov/24009866/",
    "hitTargetCount": 11
  },
  {
    "diseaseId": "felty-syndrome",
    "diseaseName": "Felty syndrome",
    "status": "dataset-verified-interaction",
    "evidenceTier": "dataset-verified-interaction",
    "targetSymbol": "FAS",
    "targetName": "Fas cell surface death receptor",
    "targetRank": 39,
    "targetScore": 0.0500044623220524,
    "moleculeHint": null,
    "datasetSource": "HPIDb",
    "interactionMethod": "anti bait coimmunoprecipitation",
    "interactionType": "physical association",
    "pathogenTaxon": "Hepatitis C virus genotype 2a (isolate JFH-1)",
    "pathogenInteractor": "Hepatitis C virus genotype 2a (isolate JFH-1) protein q99ib8-pro_0000045603",
    "pmid": "23427160",
    "title": "intact:EBI-8840058|imex:IM-26063-7",
    "url": "https://pubmed.ncbi.nlm.nih.gov/23427160/",
    "hitTargetCount": 10
  }
] satisfies ParasiteScanHit[];

export const parasiteScanHitsByDiseaseId = Object.fromEntries(
  parasiteScanHits.map((hit) => [hit.diseaseId, hit])
) as Record<string, ParasiteScanHit>;
